/*
 * Copyright (c) 2020. 7Summits Inc.
 */


public with sharing class x7sEventsTestConstants
{
    // These profiles are assumed to have full access to the 7S Event__c and related objects
//    public static final String CUSTOMER_COMMUNITY_USER       = 'Customer Community User';
 public static final String CUSTOMER_COMMUNITY_USER       = 'Customer Community Plus User Custom';
    public static final String CUSTOMER_COMMUNITY_USER_CLONE = 'Customer Community User Clone';
}