@IsTest
private class x7sMembersTestConstantsTest {
    
    @IsTest
    static void testConstants() {
        System.debug('COMPANY_COMMUNITY_PROFILE_NAME: ' + x7sMembersTestConstants.COMPANY_COMMUNITY_PROFILE_NAME);
        System.debug('PARTNER_COMMUNITY_PROFILE_NAME: ' + x7sMembersTestConstants.PARTNER_COMMUNITY_PROFILE_NAME);
        System.debug('TEST_TOPIC_COUNT: ' + x7sMembersTestConstants.TEST_TOPIC_COUNT);
    }
}